package dsa.scaler.LinkedList;

import java.util.ArrayList;
import java.util.List;

public class MidElementFromStack {
    public static void main(String[] args) {
        ArrayList<ArrayList<Integer>> testData = new ArrayList<>();

        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 170)));
        testData.add(new ArrayList<>(List.of(1, 479)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 706)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 392)));
        testData.add(new ArrayList<>(List.of(1, 903)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 383)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 719)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 668)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 142)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 548)));
        testData.add(new ArrayList<>(List.of(1, 663)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 36)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 107)));
        testData.add(new ArrayList<>(List.of(1, 943)));
        testData.add(new ArrayList<>(List.of(1, 649)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 630)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 955)));
        testData.add(new ArrayList<>(List.of(1, 841)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 932)));
        testData.add(new ArrayList<>(List.of(1, 945)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 931)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 73)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 987)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 356)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 351)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 967)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 423)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 901)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 538)));
        testData.add(new ArrayList<>(List.of(1, 484)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 375)));
        testData.add(new ArrayList<>(List.of(1, 597)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 200)));
        testData.add(new ArrayList<>(List.of(1, 485)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 789)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 894)));
        testData.add(new ArrayList<>(List.of(1, 484)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 936)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 250)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 799)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 9)));
        testData.add(new ArrayList<>(List.of(1, 610)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 201)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 797)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 623)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 39)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 157)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 56)));
        testData.add(new ArrayList<>(List.of(1, 647)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 417)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 893)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 601)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 402)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 427)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 933)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 330)));
        testData.add(new ArrayList<>(List.of(1, 693)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 146)));
        testData.add(new ArrayList<>(List.of(1, 719)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 688)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 287)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 283)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 672)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 809)));
        testData.add(new ArrayList<>(List.of(1, 946)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 322)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 197)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 660)));
        testData.add(new ArrayList<>(List.of(1, 440)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 155)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 19)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 335)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 160)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 193)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 214)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 24)));
        testData.add(new ArrayList<>(List.of(1, 62)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 506)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 143)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 901)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 414)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 897)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 695)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 20)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 695)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 19)));
        testData.add(new ArrayList<>(List.of(1, 120)));
        testData.add(new ArrayList<>(List.of(1, 801)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 927)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 228)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 110)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 424)));
        testData.add(new ArrayList<>(List.of(1, 903)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 738)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 261)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 31)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 791)));
        testData.add(new ArrayList<>(List.of(1, 189)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 852)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 714)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 59)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 358)));
        testData.add(new ArrayList<>(List.of(1, 478)));
        testData.add(new ArrayList<>(List.of(1, 114)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 429)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 406)));
        testData.add(new ArrayList<>(List.of(1, 112)));
        testData.add(new ArrayList<>(List.of(1, 836)));
        testData.add(new ArrayList<>(List.of(1, 73)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 217)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 23)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 718)));
        testData.add(new ArrayList<>(List.of(1, 586)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 297)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 735)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 458)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 964)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 676)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 994)));
        testData.add(new ArrayList<>(List.of(1, 706)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 882)));
        testData.add(new ArrayList<>(List.of(1, 414)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 679)));
        testData.add(new ArrayList<>(List.of(1, 444)));
        testData.add(new ArrayList<>(List.of(1, 674)));
        testData.add(new ArrayList<>(List.of(1, 314)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 819)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 113)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 489)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 45)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 606)));
        testData.add(new ArrayList<>(List.of(1, 182)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 293)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 562)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 814)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 825)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 760)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 28)));
        testData.add(new ArrayList<>(List.of(1, 76)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 504)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 165)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 819)));
        testData.add(new ArrayList<>(List.of(1, 751)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 649)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 914)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 547)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 866)));
        testData.add(new ArrayList<>(List.of(1, 246)));
        testData.add(new ArrayList<>(List.of(1, 319)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 473)));
        testData.add(new ArrayList<>(List.of(1, 88)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 970)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 544)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 944)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 343)));
        testData.add(new ArrayList<>(List.of(1, 61)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 147)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 749)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 784)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 749)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 956)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 585)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 343)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 949)));
        testData.add(new ArrayList<>(List.of(1, 427)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 706)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 376)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 737)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 653)));
        testData.add(new ArrayList<>(List.of(1, 839)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 453)));
        testData.add(new ArrayList<>(List.of(1, 263)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 149)));
        testData.add(new ArrayList<>(List.of(1, 318)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 201)));
        testData.add(new ArrayList<>(List.of(1, 319)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 904)));
        testData.add(new ArrayList<>(List.of(1, 644)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 283)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 403)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 620)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 393)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 962)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 972)));
        testData.add(new ArrayList<>(List.of(1, 118)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 289)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 775)));
        testData.add(new ArrayList<>(List.of(1, 816)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 978)));
        testData.add(new ArrayList<>(List.of(1, 957)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 942)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 185)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 72)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 826)));
        testData.add(new ArrayList<>(List.of(1, 630)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 117)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 680)));
        testData.add(new ArrayList<>(List.of(1, 422)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 517)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 341)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 310)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 942)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 319)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 137)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 557)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 153)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 249)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 132)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 996)));
        testData.add(new ArrayList<>(List.of(1, 270)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 463)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 38)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 601)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 449)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 316)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 398)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 852)));
        testData.add(new ArrayList<>(List.of(1, 231)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 941)));
        testData.add(new ArrayList<>(List.of(1, 148)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 362)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 570)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 235)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 558)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 550)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 338)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 715)));
        testData.add(new ArrayList<>(List.of(1, 592)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 338)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 971)));
        testData.add(new ArrayList<>(List.of(1, 569)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 374)));
        testData.add(new ArrayList<>(List.of(1, 195)));
        testData.add(new ArrayList<>(List.of(1, 827)));
        testData.add(new ArrayList<>(List.of(1, 573)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 175)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 451)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 167)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 696)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 969)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 427)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(1, 183)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 875)));
        testData.add(new ArrayList<>(List.of(1, 903)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 475)));
        testData.add(new ArrayList<>(List.of(1, 822)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(2, 0)));
        testData.add(new ArrayList<>(List.of(1, 673)));
        testData.add(new ArrayList<>(List.of(4, 0)));
        testData.add(new ArrayList<>(List.of(1, 913)));
        testData.add(new ArrayList<>(List.of(3, 0)));
        testData.add(new ArrayList<>(List.of(4, 0)));

        MidElementFromStack mefs = new MidElementFromStack();
        System.out.println(mefs.solve(testData));
    }

    public ArrayList<Integer> solve(ArrayList<ArrayList<Integer>> A) {
        ArrayList<Integer> result = new ArrayList<>();
        DLL dll = new DLL();
        for (ArrayList<Integer> currentOp: A) {
            int operation = currentOp.get(0);
            switch (operation){
                case 1 :    dll.push(currentOp.get(1));
                            System.out.println("after pushing "+currentOp.get(1));
                            dll.print();
                            break;
                case 2 :    result.add(dll.pop());
                            System.out.println("after popping");
                            dll.print();
                            break;
                case 3 :    result.add(dll.getMid());
                            System.out.println("getting mid => "+dll.getMid());
                            System.out.println("------------------------------");
                            break;
                case 4 :    dll.deleteMid();
                            System.out.println("after deleting mid");
                            dll.print();
                            break;
            }
        }
        return result;
    }

    class DLL{
        DNode head;
        DNode tail;
        DNode mid;
        int total;
        int midInd;
        public DLL(){
            total = 0;
            midInd = 0;
        }

        public void push(int val){
            // check for head, tail and mid
            DNode newNode = new DNode(val);
            if(isEmpty()){
                head = newNode;
                tail = head;
                mid = head;
                total = 1;
                midInd=1;
                return;
            }
            newNode.prev = tail;
            tail.next = newNode;
            tail = newNode;
            total++;
            int actualMid = (total >> 1)+1; //1->2->3->4->5
            if(midInd < actualMid){
                mid = mid.next;
                midInd++;
            }
        }

        public int pop(){
            if(isEmpty()){
                return -1;
            }
            int val = tail.val;
            if(total == 1){
                total = 0;
                midInd = 0;
                head = null;
                tail = null;
                mid = null;
            }else{
                tail = tail.prev;
                tail.next = null;
                total--;
                int actualMid = (total >> 1)+1;
                if(midInd > actualMid){
                    mid = mid.prev;
                    midInd--;
                }
            }

            return val;
        }

        public int getMid(){
            if(mid != null){
                return mid.val;
            }
            return -1;
        }

        public void deleteMid(){
            if(isEmpty()){
                return;
            }

            if(total == 1){
               this.pop();
               return;
            }

            if(total == 2){
                head.next = null;
                mid = head;
                tail = head;
                total--;
                midInd = 1;
                return;
            }
            try{
                mid.prev.next  = mid.next;
                mid.next.prev = mid.prev;
            }catch (Exception e){
                print();
                System.out.println(mid);
                System.out.println(head);
                System.out.println(tail);
                throw e;
            }

            if((total & 1) == 0){

                mid = mid.prev;
            }else{
                mid = mid.next;
            }

            total--;
            midInd = (total>>1)+1;
        }

        public boolean isEmpty(){
            return total == 0;
        }

        public void print(){
            DNode current = head;
            System.out.print("N <==> ");
            while(current!=null){
                System.out.print(current.val +" <==> ");
                current = current.next;
            }
            System.out.println("N");
            System.out.println("------------------------------");
        }
    }

    class DNode{
        int val;
        DNode prev;
        DNode next;

        public DNode(int val){
            this.val = val;
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder();
            sb.append("[ val => ").append(val);
            if(prev != null){
                sb.append(", prev => ").append(prev.val);
            }

            if(next != null){
                sb.append(", next => ").append(next.val);
            }

            return sb.append(" ]").toString();
        }
    }
}
